@startuml

enum UserRole {
    USER
    ADMIN
}

entity "users" as User {
    *user_id VARCHAR(21) <<not null>> <<PK>>,
    --
    email VARCHAR(100) <<not null>> <<unique>>,
    full_name VARCHAR(100) <<not null>>,
    whatsapp VARCHAR(100) <<nullable>>,
    role UserRole <<not null>> default(USER),
    password VARCHAR(100) <<not null>>,
    refresh_token VARCHAR(500) <<nullable>> <<unique>>,
    created_at TIMESTAMP default(CURRENT_TIMESTAMP),
    updated_at TIMESTAMP default(CURRENT_TIMESTAMP)
}

@enduml
