services:
  synopsis-book-category-service:
    container_name: synopsis-book-category-service
    build: 
      context:  ./
      dockerfile: Dockerfile
    image: synopsis-book-category-service:1.0.0
    env_file:
      - ./.env
    ports:
      - 1000:1000
      - 1100:1100
    networks:
      - synopsis-book-managament-network
  synopsis-book-category-service-postgres:
    container_name: synopsis-book-category-service-postgres
    image: postgres:16.0
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: synopsis-book-category-service-postgres-data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./doc/database/postgresql/postgresql.conf
        target: /etc/postgresql/postgresql.conf
    networks:
      - synopsis-book-managament-network

volumes:
  synopsis-book-category-service-postgres-data:
    name: synopsis-book-category-service-postgres-data

networks:
  synopsis-book-managament-network:
    name: synopsis-book-managament-network
    external: true
