services:
  synopsis-vault:
    container_name: synopsis-vault
    image: hashicorp/vault:1.17
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
      VAULT_API_ADDR: http://0.0.0.0:8200
    ports:
      - 8201:8200
    volumes:
      - type: bind
        source: ./config.hcl
        target: /vault/config/config.hcl
      - type: volume
        source: synopsis-vault-data
        target: /vault/data

    cap_add:
      - IPC_LOCK
    networks:
      - synopsis-book-managament-network
    command: vault server -config=/vault/config/config.hcl

volumes:
  synopsis-vault-data:
    name: synopsis-vault-data

networks:
  synopsis-book-managament-network:
    name: synopsis-book-managament-network
    external: true
